const { GoogleGenerativeAI } = require("@google/generative-ai");
const Applicant = require("./model");
const { default: mongoose } = require("mongoose");
 
require("dotenv").config();


 
// Use environment variables for API key security
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
 mongoose.connect(process.env.MONGO_URI).then(console.log("db connect hogya bhai")).catch((err)=>console.log(err));
 



async function generateResumeJSON(pdfData) {
 
console.log(pdfData);

const prompt = `
Convert the following resume text into a structured JSON format.

Resume Text:
"""
${pdfData}
"""

Output JSON format should be:
{
  "name": <name>,
  "email": <email>,
  "education":
    {
      "degree": <degree>,
      "branch" : <branch>,
      "institution": <institution>,
      "year": <year>
    },
  "experience": 
    {
      "job_title": <job_title>,
      "company": <company>,
      "start_date": <start_date>,
      "end_date": <end_date>
    },
  "skills": [
    <skill_1>,
    <skill_2>,
    ...
  ],
  "summary" <write a short summary about the candidate profile - generated by LLM based on resume data >
`;


  try {
    const result = await model.generateContent(prompt);
    console.log(result.response.text());
    let responseString = result.response.text();

     
      // Remove surrounding `"""` and extra spaces
      const cleanedString = responseString.trim().replace(/^```json|```$/g, '');
      
      // Parse the cleaned string into JSON
      const finalResponse = JSON.parse(cleanedString);

      console.log("Parsed JSON:", finalResponse);

      // Store in MongoDB
      const applicant = new Applicant(finalResponse); // Use parsed JSON object
      await applicant.save();

     

  } catch (error) {
    console.error("Error generating JSON:", error);
  }
}


module.exports=generateResumeJSON;
